### ISSUE TITLE
L1==L2 condition failing in SAMSA_score.py

### ISSUE THREAD

**Issue by tkngoutham** [eliorsulem/SAMSA#1]
Complex Sentence :  Ram went to school and played football .
Simple Sentence : Ram went to school . Ram played football .

cat scene_sentence_extraction_output/s0.txt 
[['Ram', 'went', 'to', 'school'], ['Ram', 'played', 'football']]
[['Ram', 'went', 'to', 'school', 'and', 'played', 'football', '.']]

cat scene_sentence_alignment_output/a0.txt 
[[[['Ram', 'Ram'], ['went', 'went'], ['to', 'to'], ['school', 'school']]], [[['played', 'played'], ['football', 'football'], ['Ram', 'Ram']]]]

Traceback (most recent call last):
  File "SAMSA_score.py", line 222, in <module>
    if len(t[i][j]) > match_value and j not in match:
IndexError: list index out of range

**Comment by eliorsulem** [comment]
Hi Kushwanth,

If the Simple Text is "Ram went to school. Ram played football.", then by applying scene_sentence_extraction.py,  the second line in scene_sentence_extraction_output/s0.txt should be:
[['Ram','went',to','school','.'], ['Ram', 'played', 'football','.']]
It is the segmentation of the Simple Text into sentences.

Best,
Elior
